### ISSUE TITLE
High delay while loading Blockchain section

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-ui#11]
https://login.lisk.io/blockchain usually takes very long time to load and end up with "No Blockchain" after couple retries it finally works as it should, but still takes too long.

**Comment by karmacoma** [comment]
@karek314 Yes I see the problem.

I will add more nodes to the cluster in order to share the load, this should improve things dramatically.

Closing this issue here for now, as not specific to UI. This is more related to the core performance and scalability. Something we are looking to address for sure.
