### ISSUE TITLE
Downloading / Starting apps results in wrong password

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-ui#14]
When trying to install any app from DAppStore it resulted in wrong password alert. I have tried to use 1st and 2nd passphrase, both invalid. In the same time i was able to use other functions like sending / voting

<img src="http://s8.postimg.org/wz60y1v9h/Screen_Shot_2016_03_22_at_5_40_05_PM.png">

**Comment by karmacoma** [comment]
@karek314 Each node has a master passphrase that is used to authenticate the installation / launch and removal of a dapp. This is a separate passphrase to the users' primary or secondary passphrase, known only by node operator.

I agree it's confusing, however the latest UI has been fixed with a clearer description within the modal.

**Comment by karmacoma** [comment]
@karek314 Will leave this open, as I think we can improve further.

**Comment by MaxKK** [comment]
We need to unify it.

E.g.

Please enter node master password.

Master Password

The master password is only accessible by the node owner. It's an auto generated and can be found at the end of the config.json file.
