### ISSUE TITLE
Language switcher is not working for all languages

### ISSUE THREAD

**Issue by senikk** [LiskHQ/lisk-ui#43]
Selecting norwegian "Norsk" doens't change the language to norwegian on testnet.lisk.io its still just english.

**Comment by qtipwax** [comment]
Noticed that also.  Some other languages not working.  The word "Productivity"  should be translated better for some languages also.  Since it looks like my account can not post anymore bugs or enhancements for Lisk.  I would like the reference to USD removed.  It is biased towards one country and cypto should try to move away from fiat references when possible.  Replaced with BTC value would be more appropriate in my opinion.
