### ISSUE TITLE
Transaction appear but did not affect balance

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-ui#53]
I have received incoming transaction, it has been added  on /dashboard transaction list, but did not affect balance. After jumping off and on /dashboard again it worked. But did not worked at the time tx was added.

**Comment by fix** [comment]
The socket may be disconnected for a few minutes. THis is general issues of one page app using angular for blockchains. Unlike classical ng app, most of the logic can be handled on the client and reflected later on the server. Here this is not possible since the transaction has to be sent and confirmed (10s or so) then reflected on the server.

Now the thing is that when a transaction is confirmed once, it appears on the dashboard, but the account balance is also a blockchain info from the server and has to go from unconfirmed to confirmed state. If it does not happen in the same time (because other transactions are processed), then you have a delay. We will try to make it smoother.

**Comment by fix** [comment]
This is angular latency general issue. Not sure if there is an easy fix, what do you think @karmacoma ?
